### ISSUE TITLE
Add View Compilation

### ISSUE THREAD

**Issue by rynowak** [aspnet/JitBench#23]
Compiling the views on publish is part of our user scenario for 2.0.0 and we expect it to be the default for all but local development.

This is useful for the ASP.NET team to be able to track the impact of this feature on startup, and also potentially useful for the CLR team since it requires a different set of dependencies.

**Comment by rynowak** [comment]
### Rough instructions (powershell-based):
```
#Do this before you publish
$env:MvcRazorCompileOnPublish="true"

# We need to work around https://github.com/aspnet/MvcPrecompilation/issues/123
# print this do you can remember it's value
$env:DOTNET_SHARED_STORE 

$env:DOTNET_SHARED_STORE=""

# Set this back to its original value
$env:DOTNET_SHARED_STORE="C:\Users\rynowak\git\aspnet\JitBench\.store" 
```

### With View Compilation
![image](https://cloud.githubusercontent.com/assets/1430011/25770774/2870267e-31f3-11e7-948f-a6ecb7b7f32e.png)

```
> dotnet .\MusicStore.dll
Server started in 606ms

Starting request to http://localhost:5000
warn: Microsoft.EntityFrameworkCore.Query[100102]
      Query: '(from Genre g in DbSet<Genre> select [g].Name).Take(__p_0)' uses a row limiting operation (Skip/Take) with
out OrderBy which may lead to unpredictable results.
Response: OK
Request took 628ms

Cold start time (server start + first request time): 1234ms


Running 100 requests
Steadystate min response time: 2ms
Steadystate max response time: 8ms
Steadystate average response time: 2ms

ASP.NET loaded from store
```

### Baseline
![image](https://cloud.githubusercontent.com/assets/1430011/25770759/19a04250-31f3-11e7-8a24-5fd99e914c73.png)

```
> dotnet .\MusicStore.dll
Server started in 576ms

Starting request to http://localhost:5000
warn: Microsoft.EntityFrameworkCore.Query[100102]
      Query: '(from Genre g in DbSet<Genre> select [g].Name).Take(__p_0)' uses a row limiting operation (Skip/Take) with
out OrderBy which may lead to unpredictable results.
Response: OK
Request took 2301ms

Cold start time (server start + first request time): 2877ms


Running 100 requests
Steadystate min response time: 2ms
Steadystate max response time: 8ms
Steadystate average response time: 2ms

ASP.NET loaded from store
```

**Comment by rynowak** [comment]
/cc @noahfalk @JosephTremoulet @lt72 @russellhadley @DamianEdwards @davidfowl (and others I'm probably forgetting)

This is the performance impact of taking Roslyn off of the startup path. This will be the default experience for deployed/published apps. Runtime compilation is still the default for local development.

Yeah, you saw that right. It takes less than half as long to start up when the views are compiled on publish. interestingly enough the %age of CPU time as JIT time as reported by perfview is consistently between 35%-40%.

I still think that the runtime compilation scenario is the best one to track as the *main* scenario because:
1. It's the most expensive
2. It's a superset of precompiled views

Ideally we could also automate this as a secondary metric.

-----
Github won't let me upload the perfview traces here, it says they are too big. Shoot me a mail if you want them (or use those instructions and have fun making your own).

**Comment by lt72** [comment]
+1 for adding pre-compiled views as secondary metric.

**Comment by noahfalk** [comment]
Thats a great result Ryan! For the secondary metric I'm happy to let you guys (ASP.Net) set priority, assuming you care about it and its cheap/easy to collect then I agree it would be good to have.

The 35-40% jit number is interesting, but I'm guessing what you are seeing is that Jit is running in a relatively fixed proportion to class loading and assembly loading while managed code execution time and dotnet startup time are fairly small players. It makes sense that jit <-> class loading is closely coupled, but deliberate scenario choices should be able to shift the balance between (jit + class loading) and assembly loading. For example with enough NGEN'ed images (jit+class loading) should drop near 0. Of course none of your scenarios do that by design.

**Comment by rynowak** [comment]
9bef199fe3c624d587290ec64167bac301d6543

**Comment by rynowak** [comment]
Added instructions to the readme and added the necessary dependencies
