### ISSUE TITLE
Install of shared runtime is failing

### ISSUE THREAD

**Issue by rynowak** [aspnet/JitBench#35]
See: https://github.com/dotnet/cli/issues/6517

Currently investigating workarounds

**Comment by rynowak** [comment]
I've worked around this issue for now. Still waiting for an answer about what happened to cause this break.

**Comment by sbomer** [comment]
@rynowak, are you going to put your workaround in JitBench? If not, could you share the workaround you have, since other folks are hitting this too? Thanks! :)

**Comment by rynowak** [comment]
For now I'm only invoking `dotnet-install` once and without the `-sharedruntime` parameter. I think this means that It'll be slower to acquire new builds of the shared runtime, since I'll only get what the SDK was built against.

I am not the owner of `dotnet-install`, and I am not a good person to answer questions about it. I would suggest following up with the dotnet team or adding info to the bug I opened here https://github.com/dotnet/cli/issues/6517

**Comment by rynowak** [comment]
OK this is now working again. The change here is that you have supply the `linux-x64` rid when updating the shared framework on linux. You still want to use the distro-specific rid when building the store.

Instructions are updated.
