### ISSUE TITLE
dotnet publish failing for 2.0 x86

### ISSUE THREAD

**Issue by adiaaida** [aspnet/JitBench#66]
When running through the instructions for building MusicStore using architecture x86 and rid win7-x86, and channel release/2.0.0, dotnet publish fails with the following output:

```
  MusicStore -> C:\michelm\JitBench\src\MusicStore\bin\Release\netcoreapp2.0\MusicStore.dll
  Object reference not set to an instance of an object.
     at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompileRunCommand.Execute()
     at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompileRunCommand.<Configure>b__17_0()
     at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
     at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompilationApplication.Execute(String[] args)
C:\Users\michelm\.dotnet\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0-preview1-final\build\netcoreapp2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(26,5): error MSB3073: The command "dotnet exec --runtimeconfig "C:\michelm\JitBench\src\MusicStore\bin\Release\netcoreapp2.0\MusicStore.runtimeconfig.json" --depsfile "C:\michelm\JitBench\src\MusicStore\bin\Release\netcoreapp2.0\MusicStore.deps.json" "C:\Users\michelm\.dotnet\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0-preview1-final\build\netcoreapp2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\Release\netcoreapp2.0\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code 1. [C:\michelm\JitBench\src\MusicStore\MusicStore.csproj]
```

**Comment by adiaaida** [comment]
@rynowak Is this a known issue?

**Comment by rynowak** [comment]
@pranavkm - have we seen this?

**Comment by pranavkm** [comment]
Yeah, we had reports of null refs in our preview1 \ preview2 bits. We refactored some of the underlying code since and I haven't seen this failure with our our RTM bits. Could you update to our RTM build from our nightlies?

**Comment by rynowak** [comment]
Would it meet your objectives if you tried on preview2? I just pushed a `rel/2.0.0-preview2` which is never.

**Comment by adiaaida** [comment]
I'll check it out.

**Comment by rynowak** [comment]
Did you end up turning on precompilation? https://github.com/aspnet/JitBench/blob/master/src/MusicStore/MusicStore.csproj#L22

It should be off by default and this tool won't run

**Comment by adiaaida** [comment]
I have made no changes to the build process or to any source files. I just checked and my MusicStore.csproj looks normal

**Comment by adiaaida** [comment]
The new branch worked on my local box, but it still looks like something is setting MvcRazorCompiuleOnPublish to true. Build output:

```
PS C:\michelm\JitBench\src\MusicStore> dotnet publish -c Release -f netcoreapp2.0 --manifest $env:JITBENCH_ASPNET_MANIFEST
Microsoft (R) Build Engine version 15.3.402.46929 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  MusicStore -> C:\michelm\JitBench\src\MusicStore\bin\Release\netcoreapp2.0\MusicStore.dll
  Razor view compilation for MusicStore -> obj\Release\netcoreapp2.0\MusicStore.PrecompiledViews.dll
  MusicStore -> C:\michelm\JitBench\src\MusicStore\bin\Release\netcoreapp2.0\publish\
```

Findstr output:

```
PS C:\michelm\JitBench> findstr /snp MvcRazorCompileOnPublish *
.dotnet\sdk\2.0.0-preview3-006729\Sdks\Microsoft.NET.Sdk.Web.ProjectSystem\build\netstandard1.0\Microsoft.NET.Sdk.Web.ProjectSystem.props:24:    <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
```

**Comment by rynowak** [comment]
Ah! The issue here is that my msbuild-fu is lacking.

This
```
<PropertyGroup Condition=" '$(MvcRazorCompileOnPublish)' == '' ">
    <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
</PropertyGroup>
```

Should be 
```
<PropertyGroup>
    <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
</PropertyGroup>
```

So if you want to skip precompilation pass `/p:MvcRazorCompileOnPublish=false` at the command line to `dotnet publish`.

If you're collecting data for comparison purposes it's worth collecting data with and without precompilation. This is a change to our **user experience** for 2.0.0 aimed at reducing startup time for published apps. 

If you want to want to compare apples to apples for the local dev inner loop, then you want it off.

**Comment by adiaaida** [comment]
Ah! Thank you! I'll collect numbers for both, since they both seem to work now. Thank you for looking into this!

**Comment by pranavkm** [comment]
Is this all sorted now?

**Comment by rynowak** [comment]
I'm planning to create a 2.0.0 branch today, I'll verify it there.

**Comment by pranavkm** [comment]
The precompilation tool has been superseded by build time compilation using RazorSDK. Super unlikely this is still a problem. Could we close this?

**Comment by adiaaida** [comment]
Closing.
