### ISSUE TITLE
JitBench dev branch not using master branch builds of CoreCLR

### ISSUE THREAD

**Issue by JosephTremoulet** [aspnet/JitBench#71]
When I follow the instructions in the dev branch README, I see this:

```
Setting JITBENCH_FRAMEWORK_VERSION to 2.1.0-dev-di-25621-02
```

which presumably corresponds to coreclr's [dev/defaultintf branch](https://github.com/dotnet/coreclr/tree/dev/defaultintf) rather than its master branch.

The scripts here seem to be behaving properly, but passing `-Channel master` to `Dotnet-Install.ps1` is now returning `dev-di` builds.  I don't know if we should be specifying some other `-Channel` (or even where to get a list of available channels and what they're for) or if `-Channel master` should not be returning `dev-di` builds or what, but unless we're using code that depends on the default interface features I'd like to be able to continue running against builds from coreclr's master branch.

**Comment by rynowak** [comment]
hmm that's interesting. I don't own this script - it's a copy of these https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md

Will look into this

**Comment by rynowak** [comment]
So a few details here...

We don't pull anything directly from CoreCLR - this is coming through core setup and the SDK / Shared Library path. We're just grabbing the latest SDK and shared library - not the CoreCLR directly. 

Right now if I do this, I get `2.1.0-preview2-25625-01`

/cc @eerhardt any thoughts on this?

**Comment by eerhardt** [comment]
Thanks for bringing this to my attention.

It turns out https://github.com/dotnet/core-setup/issues/3079 is causing issues with the core-setup repo.  Basically, we have 2 separate branches `master` and `dev/defaultinf` that are overwriting each other.  So sometimes `dev/defaultinf` is the `latest` and sometimes `master` is the `latest`, depending on who built last.

I'll get this fixed in core-setup.

**Comment by rynowak** [comment]
Thanks! https://github.com/dotnet/core-setup/pull/3101

**Comment by rynowak** [comment]
It sounds like this should be fixed now. let me know if there are any more problems
