### ISSUE TITLE
Enable naive steady state performance measurements

### ISSUE THREAD

**Issue by lt72** [aspnet/JitBench#9]
Measure _Requests/Second_: consider adding a loop around HttpRequest on main thread

**Comment by rynowak** [comment]
@lt72 - something like this was done here https://github.com/aspnet/JitBench/blob/dev/src/MusicStore/Program.cs#L61 

Does this meet your needs?

**Comment by lt72** [comment]
yes, it does. Down the line we should look to enable something more sophisticated, but for now I'd be happy if we can get this running reliably for a couple of months.

**Comment by rynowak** [comment]
Ok closing for now. Reopen with new requirements or create a new issue when you want more.
